### ISSUE TITLE
Add Chinese Simplified Translation

### ISSUE THREAD

**Issue by arrowrowe** [dyweb/apidoc#1]
As @at15 mentioned in dyweb/web-stuff#19, ~~we need a better language detection than [the current version](https://github.com/apidoc/apidoc/blob/master/template/locales/locale.js) as well.~~ (<- this was a mistake.)

**Comment by at15** [comment]
@arrowrowe maybe add another check if starts with `zh`  then check if it is `zh-CN` or `zh-TW` , also the file name for `zh,js` should be changed to `zh-TW` or `zh-tw`

**Comment by arrowrowe** [comment]
@at15 I add `zh-cn` and leave `zh` untouched.

See 54406e3e5a2c3873a98df47b69488bdccd005516.

@ComMouse you can push your version here.

**Comment by arrowrowe** [comment]
The origin repo [apidoc/apidoc](https://github.com/apidoc/apidoc) has 17 PRs now, among which the oldest is Jan 12, 2015......

Maybe we can use `npm i --save-dev git+ssh://git@github.com/dyweb/apidoc.git`...

**Comment by at15** [comment]
@arrowrowe yeah, I think we can keep a fork, maybe merge some other pr as well.

**Comment by arrowrowe** [comment]
Let's assume this done......
